apiVersion: v1
kind: ConfigMap
metadata:
  name: rac-config-files
data:
  config.json: |
    {
      "authConfig": {
        "tenant": "{{ .Values.authConfig.tenant }}",
        "loginApiUrl": "{{ .Values.authConfig.loginApiUrl }}",
        "restApiUrl": "{{ .Values.authConfig.restApiUrl }}",
        "ssoFlag": {{ .Values.authConfig.ssoFlag }},
        "userIdleTime": {{ .Values.authConfig.userIdleTime }},
        "userIdleTimeOut": {{ .Values.authConfig.userIdleTimeOut }},
        "tokenExpFirstWarningMinutes": {{ .Values.authConfig.tokenExpFirstWarningMinutes }},
        "tokenExpSecondWarningMinutes": {{ .Values.authConfig.tokenExpSecondWarningMinutes }},
        "auth": {
          "issuer": "{{ .Values.authConfig.auth.issuer }}",
          "clientId": "{{ .Values.authConfig.auth.clientId }}",
          "redirectUri": "{{ .Values.authConfig.auth.redirectUri }}",
          "dummyClientSecret": "{{ .Values.authConfig.auth.dummyClientSecret }}",
          "logoutUrl": "{{ .Values.authConfig.auth.logoutUrl }}",
          "idpLogoutUrl": "{{ .Values.authConfig.auth.idpLogoutUrl }}",
          "requireHttps": {{ .Values.authConfig.auth.requireHttps }},
          "idpApiKey": "{{ .Values.authConfig.auth.idpApiKey }}",
          "interceptUrls": [{{ join "," (pluck "interceptUrls" .Values.authConfig.auth | first | quote) }}],
          "responseType": "{{ .Values.authConfig.auth.responseType }}",
          "autoRefresh": {{ .Values.authConfig.auth.autoRefresh }},
          "listenToToken": "{{ .Values.authConfig.auth.listenToToken }}"
        }
      }
    }
