{{- $config := dict "configMap" (dict "authConfig" (dict
  "tenant" "NewTenant"
  "loginApiUrl" "newLoginUrl"
  "restApiUrl" "newRestApiUrl"
  "ssoFlag" false
  "userIdleTime" 1000
  "userIdleTimeOut" 300
  "tokenExpFirstWarningMinutes" 30
  "tokenExpSecondWarningMinutes" 10
  "auth" (dict
    "issuer" "newIssuer"
    "clientId" "NEW_CLIENT_ID"
    "redirectUri" "newRedirectUri"
    "dummyClientSecret" "newSecret"
    "logoutUrl" "newLogoutUrl"
    "idpLogoutUrl" "newIdpLogoutUrl"
    "requireHttps" true
    "idpApiKey" "NEW_API_KEY"
    "interceptUrls" (list "newOrigin")
    "responseType" "token"
    "autoRefresh" false
    "listenToToken" "id_token"
  )
)) }}


apiVersion: v1
kind: ConfigMap
metadata:
  name: rac-config-files
data:
  config.json: |
    {{ $config | toJson }}
